PROGRAM MAIN
  ! test various subroutines
  USE KEYS, ONLY : ACTION

  ! read in parameter file
  
  CALL READKEY

  SELECT CASE(ACTION)
  CASE('GETFPT')
     ! calculate first passage time for all particles to each node
     CALL GETFPTDRIVER
  CASE DEFAULT
     PRINT*, 'Not a valid action: ', ACTION
  END SELECT
  
CONTAINS
  SUBROUTINE GETFPTDRIVER
    ! calculate first passage time for all particles to each node
    USE KEYS, ONLY : NETFILE, NPART, STARTNODE, NSTEP, DCOEFF, OUTFILE
    USE NETWORKUTIL, ONLY : NETWORKFROMFILE, NETWORK, CLEANUPNETWORK
    USE NETWORKPROPAGATE, ONLY : RUNPROPAGATE
    IMPLICIT NONE
    TYPE(NETWORK), TARGET :: NET
    TYPE(NETWORK), POINTER :: NETP
    DOUBLE PRECISION, ALLOCATABLE :: NODEFPT(:,:)
    INTEGER :: PC, PC2, SI, FILESTATUS, COUNTER, RUN
    DOUBLE PRECISION :: MAX_FPT, MEAN_MAX_FPT, MEAN_MEAN_MAX_FPT, TOTALEDGELEN
    DOUBLE PRECISION :: MEAN_MEAN_MAX_FPT1, MEAN_MEAN_MAX_FPT2
    DOUBLE PRECISION, DIMENSION(NPART) :: FINISHTIME
    CHARACTER (LEN=1000), DIMENSION(1000) :: FILENAME
    CHARACTER (LEN=1000) :: FILENAME_TEMP
    
    NETP=>NET

    COUNTER=0
    OPEN(UNIT=99,FILE="network_names.txt",STATUS='OLD',ACTION='READ')
    DO
      COUNTER = COUNTER + 1
      READ(99,*,IOSTAT=FILESTATUS) FILENAME(COUNTER)
      IF (FILESTATUS < 0) THEN
        COUNTER = COUNTER - 1
        EXIT
      END IF
    END DO
    CLOSE(99)
    100 FORMAT (A,I3)
    PRINT 100, 'COUNTER = ', COUNTER
    
    
    !DO SI=1, COUNTER
     ! PRINT*, 'FILENAME = ', TRIM(FILENAME(SI))
    !END DO

    OPEN(UNIT=99,FILE="try.out",STATUS='REPLACE',ACTION='WRITE')
    CLOSE(99)

    DO RUN=1, COUNTER
      NETFILE = 'network_files/' // TRIM(FILENAME(RUN)) // '.net'

      CALL NETWORKFROMFILE(NETP,NETFILE)
    
    
      ALLOCATE(NODEFPT(NPART,NETP%NNODE))

      OPEN(UNIT=99,FILE="try1.out",STATUS='REPLACE',ACTION='WRITE')
      CLOSE(99)
    
      TOTALEDGELEN=0
      DO SI=1,NETP%NEDGE
        TOTALEDGELEN = TOTALEDGELEN + NETP%EDGELEN(SI)
      ENDDO
    
      MEAN_MEAN_MAX_FPT = 0;
      SI=1
      DO SI = 1, NETP%NNODE
        !CALL RUNPROPAGATE(NETP,NPART,STARTNODE,NSTEP,DCOEFF,NODEFPT,FINISHTIME)
        CALL RUNPROPAGATE(NETP,NPART,SI,NSTEP,DCOEFF,NODEFPT,FINISHTIME)

        ! for each particle output FPTs to file
        !OPEN(UNIT=99,FILE=OUTFILE)
        !DO PC = 1,NPART
        !   WRITE(99,*) PC, NODEFPT(PC,:)
        !ENDDO
        !CLOSE(99)

        MEAN_MAX_FPT = 0
        DO PC = 1,NPART
          MEAN_MAX_FPT = MEAN_MAX_FPT + FINISHTIME(PC)
        ENDDO
        MEAN_MAX_FPT = MEAN_MAX_FPT/NPART
        OPEN(UNIT=99,FILE="try1.out", ACCESS = 'append')
        110 FORMAT (I2,F20.10,F20.10,F20.10)
        WRITE(99,110) NETP%NNODE, MEAN_MAX_FPT
        CLOSE(99)
        MEAN_MEAN_MAX_FPT = MEAN_MEAN_MAX_FPT + MEAN_MAX_FPT
      ENDDO
      MEAN_MEAN_MAX_FPT1 = MEAN_MEAN_MAX_FPT/NETP%NNODE
      MEAN_MEAN_MAX_FPT2 = MEAN_MEAN_MAX_FPT/TOTALEDGELEN
      OPEN(UNIT=99,FILE='try.out', ACCESS = 'append')
      WRITE(99,110) NETP%NNODE, TOTALEDGELEN, MEAN_MEAN_MAX_FPT1, MEAN_MEAN_MAX_FPT2
      CLOSE(99)
    
      DEALLOCATE(NODEFPT)   

      CALL CLEANUPNETWORK(NETP)
    END DO
  END SUBROUTINE GETFPTDRIVER
END PROGRAM MAIN
